pipeline {
    agent {
        label "agent-1"
    } 
    environment {
        registry = "alwx1753/devops-project"
        registryCredential = 'dockerhub'
        dockerImage = ''
    }
    stages {
        stage('build docker image'){
            steps{
                script{
                    gitTag=sh(returnStdout:  true, script: "git tag --sort=-creatordate | head -n 1").trim()
                    echo "gitTag output: ${gitTag}"
                    dir('project/docker'){
                        dockerImage = docker.build registry + ":${gitTag}"
                    }
                }
            }
        }
        stage('deploy image') {
            steps{
                script{
                    docker.withRegistry( '', registryCredential ) {
                        dockerImage.push("${gitTag}")
                    }
                }
            }
        }
    }
}
