pipeline {
    agent {
        label "agent-1"
    } 
    environment {
        registry = "alwx1753/devops-project"
        registryCredential = 'dockerhub'
        dockerImage = ''
    }
    stages {
        stage('build docker image'){
            steps{
                script{
                    dir('project/docker'){
                        dockerImage = docker.build registry + ":$BUILD_NUMBER"
                        gittag = sh(returnStdout: true, script: "git tag --sort version:refname | tail -1").trim()
                        echo ${gittag}"
                    }
                }
            }
        }
        stage('deploy image') {
            steps{
                script{
                    docker.withRegistry( '', registryCredential ) {
                        dockerImage.push()
                    }
                }
            }
        }
    }
}
